service: ${self:custom.config.APP_NAME}
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  config: ${file(config/app.yml)}
  webpack:
    webpackConfig: './webpack.sls.js'
    includeModules:
      packagePath: 'package.json'
    packager: 'yarn'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.config.REGION}
  environment:
    APP_NAME: ${self:custom.config.APP_NAME}

functions:
  servePage:
    handler: 'src/server/handler.main'
    events:
      - httpApi: '*'
