service: ${self:custom.config.appName}
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  config: ${file(./config/app.config.js)}
  webpack:
    webpackConfig: './webpack.sls.js'
    includeModules:
      packagePath: 'package.json'
    packager: 'yarn'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.config.region}

functions:
  servePage:
    handler: 'src/server/handler.main'
    events:
      - httpApi: '*'
